#!/bin/bash
# these are the common settings shared by pwt programs.

DEFAULT_PWTPATH=~/.pwt
DEFAULT_EPWSPATH=~/.epws
DEFAULT_PWSPATH=~/.pws


function isset {
  if [[ -z $1 ]]; then
    return 1
  else
    return 0
  fi
}

function fexists {
  if [[ -f $1 ]]; then
    return 0
  else
    return 1
  fi
}

function dexists {
  if [[ -d $1 ]]; then
    return 0
  else
    return 1
  fi
}

function confirmed {
  if [[ $1 == "Y" || $1 == "y" ]]; then
    return 0
  else
    return 1
  fi
}
