#!/bin/bash
# pwf is a tool for finding a saved password
# usage: pwf [-e(auto encrypt)] <library> <keyword>

# Load Defaults one-liner
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" ; . $DIR/defaults
#########################

PWFEPATH=$DEFAULT_EPWSPATH
PWFPATH=$DEFAULT_PWSPATH

AUTOENCRYPT=false

usage()
{
  echo "usage: pwf [-e(auto encrypt)] <library> <keyword>"
}
while getopts e: option
do
  case $option in
    (e)
    AUTOENCRYPT=true;;
    (*)
    usage
    exit;;
  esac
  shift
done

if [[ ! -f $PWFPATH/.pwt ]]; then
  if [[ -d $PWFEPATH ]]; then
    ./pws -d $PWFEPATH $PWFPATH
  else
    ./pws -i $PWFEPATH $PWFPATH
  fi
fi

if [[ -z $1 ]]; then
  echo "You must specify a pw library to search"
  echo "e.g. pwf <mylib> <keyword>"
else
  PWFLIBRARY=$PWFPATH/pw.$1.csv
  if [[ -f $PWFLIBRARY ]]; then
    if [[ -z $2 ]]; then
      echo "You must specify a keyword to search"
      echo "e.g. pwf <mylib> <keyword>"
    else
      grep $2 $PWFLIBRARY
    fi
  else
    echo "Library $1 does not exist"
  fi
fi

if $AUTOENCRYPT == true; then
  ./pws -e
fi
