#!/bin/bash
# pwf is a tool for finding a saved password
# usage: pwf [-e(auto encrypt)] <library> <keyword>

# Load Defaults one-liner
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" ; . $DIR/defaults
#########################

PWFEPATH=$DEFAULT_EPWSPATH
PWFPATH=$DEFAULT_PWSPATH

AUTOENCRYPT=false

usage()
{
  echo "usage: pwf [-e(auto encrypt)] <library> <keyword>"
}
while getopts e: option
do
  case $option in
    (e)
    AUTOENCRYPT=true;;
    (*)
    usage
    exit;;
  esac
  shift
done

if ! fexists $PWFPATH/.pwt; then
  if dexists $PWFEPATH; then
    ./pws -d $PWFEPATH $PWFPATH
  else
    ./pws -i $PWFEPATH $PWFPATH
  fi
fi

if isset $1; then
  library_name=$1
  PWFLIBRARY=$PWFPATH/pw.$1.csv
  shift
  if [[ -f $PWFLIBRARY ]]; then
    if isset $1; then
      grep $1 $PWFLIBRARY
    else
      echo "You must specify a keyword to search"
      echo "e.g. pwf <mylib> <keyword>"
    fi
  else
    echo "Library $library_name does not exist"
  fi
else
  echo "You must specify a pw library to search"
  echo "e.g. pwf <mylib> <keyword>"
fi

if $AUTOENCRYPT == true; then
  ./pws -e
fi
